version: '3.8'

services:

  next:
    labels:
      shipyard.route: '/'
      shipyard.securityContext: '{"privileged": true, "capabilities": {"add":["SYS_ADMIN"]}}'
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - './pages:/app/pages'
      - './public:/app/public'
      - './src:/app/src'
      - './style:/app/style'
