version: '3.8'

services:

  433_next:
    labels:
      shipyard.route: '/'
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - './pages:/app/pages'
      - './public:/app/public'
      - './src:/app/src'
      - './style:/app/style'
